{"name": "test_lambdatest_radio_button_demo_value", "status": "failed", "statusDetails": {"message": "AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following 2 failures were found in \"test_lambdatest_radio_button_demo_value\" (DEMOPytest.test_assertions_soft.AssertionsTest):\n+----------------------+----------------------+----------------------+\n Failure 1 (\"Verify Gender, Title & Age Group\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"C:\\Users\\M1LESPINOS\\PycharmProjects\\pytest_with_selenium\\DEMOPytest\\test_assertions_soft.py\", line 32, in test_lambdatest_radio_button_demo_value\n    self.soft_assert(self.assertIs,\n  File \"C:\\Users\\M1LESPINOS\\PycharmProjects\\pytest_with_selenium\\.venv\\Lib\\site-packages\\softest\\case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"C:\\Users\\M1LESPINOS\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\unittest\\case.py\", line 1154, in assertIs\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"C:\\Users\\M1LESPINOS\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\unittest\\case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: 'Male' is not 'Male' : Gender Is Not Correct\n\n-+ [1/2] +-\n\n+----------------------+----------------------+----------------------+\n Failure 2 (\"Verify Gender, Title & Age Group\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"C:\\Users\\M1LESPINOS\\PycharmProjects\\pytest_with_selenium\\DEMOPytest\\test_assertions_soft.py\", line 36, in test_lambdatest_radio_button_demo_value\n    self.soft_assert(self.assertIn,\n  File \"C:\\Users\\M1LESPINOS\\PycharmProjects\\pytest_with_selenium\\.venv\\Lib\\site-packages\\softest\\case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"C:\\Users\\M1LESPINOS\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\unittest\\case.py\", line 1140, in assertIn\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"C:\\Users\\M1LESPINOS\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\unittest\\case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '51' not found in '15 - 50' : Age Group Is Not Correct\n\n-+ [2/2] +-", "trace": "self = <DEMOPytest.test_assertions_soft.AssertionsTest testMethod=test_lambdatest_radio_button_demo_value>\n\n    def test_lambdatest_radio_button_demo_value(self):\n        driver = webdriver.Chrome()\n        driver.maximize_window()\n        driver.get(\"https://www.lambdatest.com/selenium-playground/radiobutton-demo\")\n        driver.find_element(By.XPATH,\n                            \"//h4[contains(text(),'Gender')]\"\n                            \"//following::input[@value='Male']\").click()\n        driver.find_element(By.XPATH,\n                            \"//h4[contains(text(),'Age : ')]\"\n                            \"//following::input[@value='15 - 50']\").click()\n        driver.find_element(By.XPATH,\n                            \"//button[text()='Get values']\").click()\n        gender = driver.find_element(By.CSS_SELECTOR,\n                                     \".genderbutton\").text\n        age_group = driver.find_element(By.CSS_SELECTOR,\n                                        \".groupradiobutton\").text\n        print(\"Gender Object: \\t\", id(gender))\n        print(\"Male Object  : \\t\", id(\"Male\"))\n        self.soft_assert(self.assertIs,\n        \"Male\", gender, \"Gender Is Not Correct\")\n        self.soft_assert(self.assertTrue,\n                         driver.title.__contains__(\"Selenium Grid Online\"))\n        self.soft_assert(self.assertIn,\n        \"51\", age_group, \"Age Group Is Not Correct\")\n>       self.assert_all(\"Verify Gender, Title & Age Group\")\n\nDEMOPytest\\test_assertions_soft.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n.venv\\Lib\\site-packages\\softest\\case.py:139: in assert_all\n    self.fail(''.join(failure_output))\nE   AssertionError: ++++ soft assert failure details follow below ++++\nE   \nE   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nE   The following 2 failures were found in \"test_lambdatest_radio_button_demo_value\" (DEMOPytest.test_assertions_soft.AssertionsTest):\nE   +----------------------+----------------------+----------------------+\nE    Failure 1 (\"Verify Gender, Title & Age Group\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"C:\\Users\\M1LESPINOS\\PycharmProjects\\pytest_with_selenium\\DEMOPytest\\test_assertions_soft.py\", line 32, in test_lambdatest_radio_button_demo_value\nE       self.soft_assert(self.assertIs,\nE     File \"C:\\Users\\M1LESPINOS\\PycharmProjects\\pytest_with_selenium\\.venv\\Lib\\site-packages\\softest\\case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"C:\\Users\\M1LESPINOS\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\unittest\\case.py\", line 1154, in assertIs\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"C:\\Users\\M1LESPINOS\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\unittest\\case.py\", line 703, in fail\nE       raise self.failureException(msg)\nE   AssertionError: 'Male' is not 'Male' : Gender Is Not Correct\nE   \nE   -+ [1/2] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 2 (\"Verify Gender, Title & Age Group\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"C:\\Users\\M1LESPINOS\\PycharmProjects\\pytest_with_selenium\\DEMOPytest\\test_assertions_soft.py\", line 36, in test_lambdatest_radio_button_demo_value\nE       self.soft_assert(self.assertIn,\nE     File \"C:\\Users\\M1LESPINOS\\PycharmProjects\\pytest_with_selenium\\.venv\\Lib\\site-packages\\softest\\case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"C:\\Users\\M1LESPINOS\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\unittest\\case.py\", line 1140, in assertIn\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"C:\\Users\\M1LESPINOS\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\unittest\\case.py\", line 703, in fail\nE       raise self.failureException(msg)\nE   AssertionError: '51' not found in '15 - 50' : Age Group Is Not Correct\nE   \nE   -+ [2/2] +-"}, "attachments": [{"name": "stdout", "source": "16b5bee9-4782-4104-8bd6-ba57d9c6613d-attachment.txt", "type": "text/plain"}], "start": 1706622386885, "stop": 1706622391870, "uuid": "1861ad3f-2930-4d7f-a520-6ae6eaa93e68", "historyId": "1b98578e26336915dfaae6bd8c71695f", "testCaseId": "1b98578e26336915dfaae6bd8c71695f", "fullName": "DEMOPytest.test_assertions_soft.AssertionsTest#test_lambdatest_radio_button_demo_value", "labels": [{"name": "parentSuite", "value": "DEMOPytest"}, {"name": "suite", "value": "test_assertions_soft"}, {"name": "subSuite", "value": "AssertionsTest"}, {"name": "host", "value": "L500970-MX"}, {"name": "thread", "value": "11580-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "DEMOPytest.test_assertions_soft"}]}